version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # 使用 Python 3.8 Docker 镜像
    steps:
      - checkout  # 检出代码到工作目录

      - run:
          name: Install dependencies  # 安装依赖
          command: |
            python -m pip install --upgrade pip
            pip install pytest

      - run:
          name: Run tests  # 运行测试
          command: pytest carpet_test/carpet_test.py

workflows:
  version: 2
  test:
    jobs:
      - test
